
name: Manual Pyinstaller [Windows]

# Builds using Pyinstaller

on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pymupdf
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          #pyinstaller_ver: '==5.13.2'
          spec: app.py
          #requirements: 'requirements.txt'
          #upload_exe_with_name: 'My executable'
          options: --onefile, --windowed  # --name "My App",
          #spec_options: # any custom arguments you want like: `--debug`

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: executable-windows
          path: dist/*
      
